name: flame_tutorial
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 2d game engine
  flame: ^1.2.0
  # work with audio
  flame_audio: ^1.2.0
  # to load sprite sheet file which was created by the texturepacker
  flame_texturepacker: ^2.0.0+2
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/game_1/
    - assets/audio/game_2/
    - assets/images/game_3/
